version: '3.3'

services:
  postgres-coursework-db:
    image: 'postgres:12.0'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=course-work
    ports:
      - 65432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-coursework-db
  spring-boot-docker-container:
    image: 'springboot-docker-container'
    container_name: springboot-docker-container
    ports:
    - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres-coursework-db
volumes:
  postgres-data:

networks:
  postgres-coursework-db:
    external: true
