server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:65432/course-work?stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  flyway:
    enabled: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
  mail:
    host: smtp.googlemail.com
    username: epam.project.traulko@gmail.com
    password: project.traulko
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
app:
  accountConfirmURL: http://localhost:8080/api/auth/confirm/
  passwordResetURL: 1